const PPIDAllTimeActionTypes = {
    GET_DATA_PPID_ALL_TIME: 'GET_DATA_PPID_ALL_TIME',
    GET_DATA_PPID_ALL_TIME_SUCCESS: 'GET_DATA_PPID_ALL_TIME_SUCCESS',
    GET_DATA_PPID_ALL_TIME_FAILED: 'GET_DATA_PPID_ALL_TIME_FAILED'
}

export default PPIDAllTimeActionTypes;