const PPIDAllNecessarilyTypes = {
  GET_DATA_PPID_NECESSARILY: 'GET_DATA_PPID_NECESSARILY',
  GET_DATA_PPID_NECESSARILY_SUCCESS: 'GET_DATA_PPID_NECESSARILY_SUCCESS',
  GET_DATA_PPID_NECESSARILY_FAILED: 'GET_DATA_PPID_NECESSARILY_FAILED',
};

export default PPIDAllNecessarilyTypes;
