const FormStyles = {
    input: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
      },
      title: {
        flex: 1,
      },
      form: {
        flex: 2,
      },
      label: {
        fontSize: 14,
      },
      textInput: {
        borderColor: 'gray',
        width: '100%',
        borderWidth: 1,
        borderRadius: 5,
        fontSize: 13,
        height: 40,
        paddingTop: 5,
        paddingLeft: 10,
        paddingBottom: 5,
        marginBottom: 10,
      },
      textInputArea: {
        borderColor: 'gray',
        width: '100%',
        height: 100,
        borderWidth: 1,
        borderRadius: 5,
        fontSize: 13,
        paddingTop: 5,
        paddingLeft: 10,
        paddingBottom: 5,
        marginBottom: 10,
        textAlignVertical: 'top',
      },
      textInputCheckbox: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
      },
      titleTextInputCheckbox: {
        fontSize: 10,
      },
      textInputSelect: {
        borderWidth: 1,
        height: 40,
        display: 'flex',
        borderColor: 'gray',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        marginBottom: 10,
      },
      textInputFile: {
        borderWidth: 1,
        height: 40,
        display: 'flex',
        borderColor: 'gray',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        marginBottom: 10,
        width: '100%',
      },
      inputFile: {
        height: 30,
        backgroundColor: 'gray',
        paddingHorizontal: 10,
        display: 'flex',
        alignItems: 'center',
        borderRadius: 4,
        marginLeft: 5,
        justifyContent: 'center',
      },
      seoContent: {
        paddingHorizontal: 10,
      },
      actionButton: {
        marginTop: 30,
        paddingBottom: 80,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-end',
      },
      btn: {
        width: 80,
        height: 25,
        marginLeft: 20,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: 12,
        borderRadius: 5,
      },
}

export default FormStyles;