const LoginActionTypes = {
  POST_LOGIN: 'POST_LOGIN',
  POST_LOGIN_SUCCESS: 'POST_LOGIN_SUCCESS',
  POST_LOGIN_FAILED: 'POST_LOGIN_FAILED',

  POST_LOGOUT: 'POST_LOGOUT',
  POST_LOGOUT_SUCCESS: 'POST_LOGOUT_SUCCESS',
  POST_LOGOUT_FAILED: 'POST_LOGOUT_FAILED',
};

export default LoginActionTypes;
