const PPIDAllPeriodicallyTypes = {
  GET_DATA_PPID_PERIODICALLY: 'GET_DATA_PPID_PERIODICALLY',
  GET_DATA_PPID_PERIODICALLY_SUCCESS: 'GET_DATA_PPID_PERIODICALLY_SUCCESS',
  GET_DATA_PPID_PERIODICALLY_FAILED: 'GET_DATA_PPID_PERIODICALLY_FAILED',
};

export default PPIDAllPeriodicallyTypes;
