const PPIDNeedResponseTypes = {
    GET_PPID_NEED_RESPONSE: 'GET_PPID_NEED_RESPONSE',
    GET_PPID_NEED_RESPONSE_SUCCESS: 'GET_PPID_NEED_RESPONSE_SUCCESS',
    GET_PPID_NEED_RESPONSE_FAILED: 'GET_PPID_NEED_RESPONSE_FAILED',
  };
  
  export default PPIDNeedResponseTypes;
  