const PPIDNeedForwardTypes = {
    GET_PPID_NEED_FORWARD: 'GET_PPID_NEED_FORWARD',
    GET_PPID_NEED_FORWARD_SUCCESS: 'GET_PPID_NEED_FORWARD_SUCCESS',
    GET_PPID_NEED_FORWARD_FAILED: 'GET_PPID_NEED_FORWARD_FAILED',
  };
  
  export default PPIDNeedForwardTypes;
  