const BeritaDanSiaranActionTypes = {
  GET_DATA_BERITA_DAN_SIARAN: 'GET_DATA_BERITA_DAN_SIARAN',
  GET_DATA_BERITA_DAN_SIARAN_SUCCESS: 'GET_DATA_BERITA_DAN_SIARAN_SUCCESS',
  GET_DATA_BERITA_DAN_SIARAN_FAILED: 'GET_DATA_BERITA_DAN_SIARAN_FAILED',

  POST_DATA_BERITA_DAN_SIARAN: 'POST_DATA_BERITA_DAN_SIARAN',
  POST_DATA_BERITA_DAN_SIARAN_SUCCESS: 'POST_DATA_BERITA_DAN_SIARAN_SUCCESS',
  POST_DATA_BERITA_DAN_SIARAN_FAILED: 'POST_DATA_BERITA_DAN_SIARAN_FAILED',

  UPDATE_DATA_BERITA_DAN_SIARAN: 'UPDATE_DATA_BERITA_DAN_SIARAN',
  UPDATE_DATA_BERITA_DAN_SIARAN_SUCCESS:
    'UPDATE_DATA_BERITA_DAN_SIARAN_SUCCESS',
  UPDATE_DATA_BERITA_DAN_SIARAN_FAILED: 'UPDATE_DATA_BERITA_DAN_SIARAN_FAILED',

  DELETE_DATA_BERITA_DAN_SIARAN: 'DELETE_DATA_BERITA_DAN_SIARAN',
  DELETE_DATA_BERITA_DAN_SIARAN_SUCCESS:
    'DELETE_DATA_BERITA_DAN_SIARAN_SUCCESS',
  DELETE_DATA_BERITA_DAN_SIARAN_FAILED: 'DELETE_DATA_BERITA_DAN_SIARAN_FAILED',
};

export default BeritaDanSiaranActionTypes;
